-- MySQL Script generated by MySQL Workbench
-- Fri Jul 10 10:28:13 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `activo` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` VARCHAR(36) NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `email` VARCHAR(150) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `estado` ENUM('activo', 'inactivo', 'bloqueado') NULL,
  `intentos_fallidos` TINYINT NULL,
  `ultimo_acceso` DATETIME NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuarios_roles_idx` (`roles_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_roles`
    FOREIGN KEY (`roles_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sesiones_activas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sesiones_activas` (
  `id` INT NOT NULL,
  `token_jwt` VARCHAR(512) NOT NULL,
  `dispositivo` VARCHAR(255) NULL,
  `ip` VARCHAR(45) NULL,
  `expira_en` DATETIME NULL,
  `activa` TINYINT NULL,
  `usuarios_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sesiones_activas_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_sesiones_activas_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`otp_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`otp_tokens` (
  `id` INT NOT NULL,
  `codigo` VARCHAR(8) NOT NULL,
  `expira_en` DATETIME NOT NULL,
  `usado` TINYINT NULL,
  `creado_en` DATETIME NOT NULL,
  `usuarios_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_otp_tokens_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_otp_tokens_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mesas` (
  `id` VARCHAR(36) NOT NULL,
  `numero` INT NOT NULL,
  `estado` ENUM('disponible', 'ocupada', 'en_cobro') NOT NULL,
  `codigo_qr` VARCHAR(100) NULL,
  `creado_en` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `codigo_qr_UNIQUE` (`codigo_qr` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `id` VARCHAR(36) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NULL,
  `telefono` VARCHAR(20) NULL,
  `estado` ENUM('activo', 'inactivo') NOT NULL,
  `delete_at` DATETIME NULL,
  `usuarios_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_clientes_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedidos` (
  `id` VARCHAR(36) NOT NULL,
  `estado` ENUM('abierto', 'cerrado', 'cancelado') NOT NULL,
  `sincronizado` TINYINT NULL,
  `creado_en` DATETIME NOT NULL,
  `mesas_id` VARCHAR(36) NOT NULL,
  `usuarios_id` VARCHAR(36) NOT NULL,
  `clientes_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedidos_mesas1_idx` (`mesas_id` ASC) VISIBLE,
  INDEX `fk_pedidos_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_pedidos_clientes1_idx` (`clientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_mesas1`
    FOREIGN KEY (`mesas_id`)
    REFERENCES `mydb`.`mesas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `mydb`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historial_cambios_mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historial_cambios_mesa` (
  `id` INT NOT NULL,
  `pedidos_trasladados` JSON NULL,
  `fue_reversion` TINYINT NULL,
  `creado_en` DATETIME NOT NULL,
  `mesas_id` VARCHAR(36) NOT NULL,
  `mesas_id1` VARCHAR(36) NOT NULL,
  `usuarios_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_historial_cambios_mesa_mesas1_idx` (`mesas_id` ASC) VISIBLE,
  INDEX `fk_historial_cambios_mesa_mesas2_idx` (`mesas_id1` ASC) VISIBLE,
  INDEX `fk_historial_cambios_mesa_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_historial_cambios_mesa_mesas1`
    FOREIGN KEY (`mesas_id`)
    REFERENCES `mydb`.`mesas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historial_cambios_mesa_mesas2`
    FOREIGN KEY (`mesas_id1`)
    REFERENCES `mydb`.`mesas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historial_cambios_mesa_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagos` (
  `id` VARCHAR(20) NOT NULL,
  `metodo_de_pago` ENUM('efectivo', 'nequi', 'daviplata', 'tarjeta') NOT NULL,
  `total_seleccionado` DECIMAL(10) NOT NULL,
  `verificacion_estado` ENUM('pendiente', 'verificado', 'rechazado') NOT NULL,
  `estado` ENUM('pendiente', 'pagado', 'cancelado') NULL,
  `origen` ENUM('mesera', 'cliente_web') NULL,
  `creado_en` DATETIME NOT NULL,
  `pedidos_id` VARCHAR(36) NOT NULL,
  `usuarios_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `estado_UNIQUE` (`estado` ASC) VISIBLE,
  INDEX `fk_pagos_pedidos1_idx` (`pedidos_id` ASC) VISIBLE,
  INDEX `fk_pagos_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_pagos_pedidos1`
    FOREIGN KEY (`pedidos_id`)
    REFERENCES `mydb`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sesiones_division`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sesiones_division` (
  `id` VARCHAR(36) NOT NULL,
  `modalidad` ENUM('por_items', 'equitativa', 'total') NOT NULL,
  `usuarios_id` VARCHAR(36) NOT NULL,
  `mesas_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sesiones_division_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_sesiones_division_mesas1_idx` (`mesas_id` ASC) VISIBLE,
  CONSTRAINT `fk_sesiones_division_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sesiones_division_mesas1`
    FOREIGN KEY (`mesas_id`)
    REFERENCES `mydb`.`mesas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `activo` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedores` (
  `id` VARCHAR(36) NOT NULL,
  `telefono` VARCHAR(20) NULL,
  `email` VARCHAR(150) NULL,
  `contacto_nombre` VARCHAR(100) NULL,
  `estado` ENUM('activo', 'inactivo') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`compras` (
  `id` VARCHAR(36) NOT NULL,
  `estado` ENUM('pendiente', 'recibida', 'cancelada') NOT NULL,
  `total_estimado` DECIMAL(10,2) NOT NULL,
  `total_recibido` DECIMAL(10,2) NOT NULL,
  `creado_en` DATETIME NOT NULL,
  `proveedores_id` VARCHAR(36) NOT NULL,
  `usuarios_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_compras_proveedores1_idx` (`proveedores_id` ASC) VISIBLE,
  INDEX `fk_compras_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_compras_proveedores1`
    FOREIGN KEY (`proveedores_id`)
    REFERENCES `mydb`.`proveedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historial_costos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historial_costos` (
  `id` VARCHAR(36) NOT NULL,
  `costo_unitario` DECIMAL(10,2) NOT NULL,
  `costo_promedio_ponderado` DECIMAL(10,2) NOT NULL,
  `creado_en` DATETIME NOT NULL,
  `compras_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_historial_costos_compras1_idx` (`compras_id` ASC) VISIBLE,
  CONSTRAINT `fk_historial_costos_compras1`
    FOREIGN KEY (`compras_id`)
    REFERENCES `mydb`.`compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `id` VARCHAR(36) NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `codigo` VARCHAR(50) NOT NULL,
  `precio_venta` DECIMAL(10,2) NOT NULL,
  `costo_promedio_ponderado` DECIMAL(10,2) NOT NULL,
  `cantidad_disponible` INT NOT NULL,
  `stock_minimo` INT NOT NULL,
  `estado` ENUM('activo', 'inactivo') NOT NULL,
  `categorias_id` INT NOT NULL,
  `proveedores_id` VARCHAR(36) NOT NULL,
  `historial_costos_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE,
  INDEX `fk_productos_categorias1_idx` (`categorias_id` ASC) VISIBLE,
  INDEX `fk_productos_proveedores1_idx` (`proveedores_id` ASC) VISIBLE,
  INDEX `fk_productos_historial_costos1_idx` (`historial_costos_id` ASC) VISIBLE,
  CONSTRAINT `fk_productos_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `mydb`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_proveedores1`
    FOREIGN KEY (`proveedores_id`)
    REFERENCES `mydb`.`proveedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_historial_costos1`
    FOREIGN KEY (`historial_costos_id`)
    REFERENCES `mydb`.`historial_costos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movimientos_inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movimientos_inventario` (
  `id` VARCHAR(36) NOT NULL,
  `tipo` ENUM('compra', 'venta', 'merma', 'ajuste') NOT NULL,
  `cantidad` INT NOT NULL,
  `stock_antes` INT NOT NULL,
  `stock_despues` INT NOT NULL,
  `referencia_tipo` ENUM('pedido', 'compra', 'merma', 'ajuste') NOT NULL,
  `productos_id` VARCHAR(36) NOT NULL,
  `usuarios_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movimientos_inventario_productos1_idx` (`productos_id` ASC) VISIBLE,
  INDEX `fk_movimientos_inventario_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_movimientos_inventario_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `mydb`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimientos_inventario_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alertas_inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alertas_inventario` (
  `id` VARCHAR(36) NOT NULL,
  `tipo` ENUM('bajo', 'agotado') NOT NULL,
  `estado` ENUM('activa', 'vista', 'silenciada', 'resuelta') NOT NULL,
  `creado_en` DATETIME NOT NULL,
  `productos_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_alertas_inventario_productos1_idx` (`productos_id` ASC) VISIBLE,
  CONSTRAINT `fk_alertas_inventario_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `mydb`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`refrigeradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`refrigeradores` (
  `id` VARCHAR(36) NOT NULL,
  `nombre` VARCHAR(80) NOT NULL,
  `ubicacion` VARCHAR(45) NULL,
  `estado` ENUM('activa', 'mantenimiento', 'apagada') NOT NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`refrigerador_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`refrigerador_stock` (
  `id` VARCHAR(36) NOT NULL,
  `cantidad_disponible` INT NOT NULL,
  `cantidad_minima` INT NOT NULL,
  `updated_at` DATETIME NULL,
  `refrigeradores_id` VARCHAR(36) NOT NULL,
  `productos_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_refrigerador_stock_refrigeradores1_idx` (`refrigeradores_id` ASC) VISIBLE,
  INDEX `fk_refrigerador_stock_productos1_idx` (`productos_id` ASC) VISIBLE,
  CONSTRAINT `fk_refrigerador_stock_refrigeradores1`
    FOREIGN KEY (`refrigeradores_id`)
    REFERENCES `mydb`.`refrigeradores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_refrigerador_stock_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `mydb`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compra_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`compra_items` (
  `id` VARCHAR(36) NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `compras_id` VARCHAR(36) NOT NULL,
  `productos_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_compra_items_compras1_idx` (`compras_id` ASC) VISIBLE,
  INDEX `fk_compra_items_productos1_idx` (`productos_id` ASC) VISIBLE,
  CONSTRAINT `fk_compra_items_compras1`
    FOREIGN KEY (`compras_id`)
    REFERENCES `mydb`.`compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_items_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `mydb`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido_items` (
  `id` VARCHAR(36) NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `pedido_id` VARCHAR(36) NOT NULL,
  `producto_id` VARCHAR(36) NOT NULL,
  `cantidad_pedida` INT NOT NULL,
  `cantidad_pagada` INT NULL,
  `estado` ENUM('enviado', 'servido', 'preparando', 'cancelado') NOT NULL,
  `pedidos_id` VARCHAR(36) NOT NULL,
  `productos_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedido_items_pedidos1_idx` (`pedidos_id` ASC) VISIBLE,
  INDEX `fk_pedido_items_productos1_idx` (`productos_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_items_pedidos1`
    FOREIGN KEY (`pedidos_id`)
    REFERENCES `mydb`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_items_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `mydb`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`activos_juego`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`activos_juego` (
  `id` VARCHAR(36) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `estado` ENUM('disponible', 'ocupado', 'mantenimiento') NOT NULL,
  `tipo` ENUM('tejo', 'billar', 'juego') NOT NULL,
  `precio_hora` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sesiones_juego`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sesiones_juego` (
  `id` VARCHAR(36) NOT NULL,
  `tipo_juego` ENUM('tejo', 'billar', 'juego') NOT NULL,
  `costo_total` DECIMAL(10,2) NULL,
  `estado` ENUM('activa', 'cerrada', 'cancelada') NOT NULL,
  `activos_juego_id` VARCHAR(36) NOT NULL,
  `mesas_id` VARCHAR(36) NOT NULL,
  `iniciada_por` VARCHAR(36) NOT NULL,
  `cerrada_por` VARCHAR(36) NOT NULL,
  `pedido_items_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sesiones_juego_activos_juego1_idx` (`activos_juego_id` ASC) VISIBLE,
  INDEX `fk_sesiones_juego_mesas1_idx` (`mesas_id` ASC) VISIBLE,
  INDEX `fk_sesiones_juego_usuarios1_idx` (`iniciada_por` ASC) VISIBLE,
  INDEX `fk_sesiones_juego_usuarios2_idx` (`cerrada_por` ASC) VISIBLE,
  INDEX `fk_sesiones_juego_pedido_items1_idx` (`pedido_items_id` ASC) VISIBLE,
  CONSTRAINT `fk_sesiones_juego_activos_juego1`
    FOREIGN KEY (`activos_juego_id`)
    REFERENCES `mydb`.`activos_juego` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sesiones_juego_mesas1`
    FOREIGN KEY (`mesas_id`)
    REFERENCES `mydb`.`mesas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sesiones_juego_usuarios1`
    FOREIGN KEY (`iniciada_por`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sesiones_juego_usuarios2`
    FOREIGN KEY (`cerrada_por`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sesiones_juego_pedido_items1`
    FOREIGN KEY (`pedido_items_id`)
    REFERENCES `mydb`.`pedido_items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pausas_sesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pausas_sesion` (
  `id` VARCHAR(36) NOT NULL,
  `inicio_pausa` DATETIME NOT NULL,
  `fin_pausa` DATETIME NOT NULL,
  `motivo` VARCHAR(200) NULL,
  `sesiones_juego_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pausas_sesion_sesiones_juego1_idx` (`sesiones_juego_id` ASC) VISIBLE,
  CONSTRAINT `fk_pausas_sesion_sesiones_juego1`
    FOREIGN KEY (`sesiones_juego_id`)
    REFERENCES `mydb`.`sesiones_juego` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rondas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rondas` (
  `id` VARCHAR(36) NOT NULL,
  `numero_ronda` INT NOT NULL,
  `resultado` ENUM('pareja_a', 'pareja_b') NULL,
  `estado` ENUM('activa', 'finalizada') NOT NULL,
  `consumo_asignado` TINYINT NULL,
  `sesiones_juego_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rondas_sesiones_juego1_idx` (`sesiones_juego_id` ASC) VISIBLE,
  CONSTRAINT `fk_rondas_sesiones_juego1`
    FOREIGN KEY (`sesiones_juego_id`)
    REFERENCES `mydb`.`sesiones_juego` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`jugadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jugadores` (
  `id` VARCHAR(36) NOT NULL,
  `nombre` VARCHAR(80) NULL,
  `creado_en` DATETIME NULL,
  `mesas_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_jugadores_mesas1_idx` (`mesas_id` ASC) VISIBLE,
  CONSTRAINT `fk_jugadores_mesas1`
    FOREIGN KEY (`mesas_id`)
    REFERENCES `mydb`.`mesas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ronda_jugadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ronda_jugadores` (
  `id` VARCHAR(36) NOT NULL,
  `pareja` ENUM('a', 'b') NULL,
  `es_perdedor` TINYINT NULL,
  `rondas_id` VARCHAR(36) NOT NULL,
  `jugadores_id` VARCHAR(36) NOT NULL,
  `pedido_items_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ronda_jugadores_rondas1_idx` (`rondas_id` ASC) VISIBLE,
  INDEX `fk_ronda_jugadores_jugadores1_idx` (`jugadores_id` ASC) VISIBLE,
  INDEX `fk_ronda_jugadores_pedido_items1_idx` (`pedido_items_id` ASC) VISIBLE,
  CONSTRAINT `fk_ronda_jugadores_rondas1`
    FOREIGN KEY (`rondas_id`)
    REFERENCES `mydb`.`rondas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ronda_jugadores_jugadores1`
    FOREIGN KEY (`jugadores_id`)
    REFERENCES `mydb`.`jugadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ronda_jugadores_pedido_items1`
    FOREIGN KEY (`pedido_items_id`)
    REFERENCES `mydb`.`pedido_items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historial_estados_activo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historial_estados_activo` (
  `id` VARCHAR(36) NOT NULL,
  `estado_anterior` ENUM('disponible', 'ocupado', 'mantenimiento') NOT NULL,
  `estado_nuevo` ENUM('disponible', 'ocupado', 'mantenimiento') NOT NULL,
  `motivo` VARCHAR(300) NULL,
  `tipo_mantenimiento` ENUM('correctivo', 'preventivo') NULL,
  `activos_juego_id` VARCHAR(36) NOT NULL,
  `usuarios_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_historial_estados_activo_activos_juego1_idx` (`activos_juego_id` ASC) VISIBLE,
  INDEX `fk_historial_estados_activo_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_historial_estados_activo_activos_juego1`
    FOREIGN KEY (`activos_juego_id`)
    REFERENCES `mydb`.`activos_juego` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historial_estados_activo_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dispositivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dispositivos` (
  `id` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(50) NULL,
  `activo` TINYINT NULL,
  `ultima_sincronizacion` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cola_eventos_offline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cola_eventos_offline` (
  `id` VARCHAR(36) NOT NULL,
  `dispositivo_id` VARCHAR(100) NOT NULL,
  `tipo_evento` VARCHAR(100) NOT NULL,
  `payload` JSON NOT NULL,
  `estado` ENUM('pendiente', 'sincronizado', 'fallido') NOT NULL,
  `intento_numero` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conflictos_sincronizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conflictos_sincronizacion` (
  `id` VARCHAR(36) NOT NULL,
  `tipo_conflicto` ENUM('stock_negativo', 'version_error') NULL,
  `estado` ENUM('auto_resuelto', 'pendiente_manual') NOT NULL,
  `cola_eventos_offline_id` VARCHAR(36) NOT NULL,
  `dispositivos_id` VARCHAR(100) NOT NULL,
  `resuelto_por` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_conflictos_sincronizacion_cola_eventos_offline1_idx` (`cola_eventos_offline_id` ASC) VISIBLE,
  INDEX `fk_conflictos_sincronizacion_dispositivos1_idx` (`dispositivos_id` ASC) VISIBLE,
  INDEX `fk_conflictos_sincronizacion_usuarios1_idx` (`resuelto_por` ASC) VISIBLE,
  CONSTRAINT `fk_conflictos_sincronizacion_cola_eventos_offline1`
    FOREIGN KEY (`cola_eventos_offline_id`)
    REFERENCES `mydb`.`cola_eventos_offline` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conflictos_sincronizacion_dispositivos1`
    FOREIGN KEY (`dispositivos_id`)
    REFERENCES `mydb`.`dispositivos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conflictos_sincronizacion_usuarios1`
    FOREIGN KEY (`resuelto_por`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reportes_generados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reportes_generados` (
  `id` VARCHAR(36) NOT NULL,
  `tipo` ENUM('diario', 'mensual', 'anual') NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `datos_json` JSON NULL,
  `archivo_url` VARCHAR(500) NULL,
  `creado_en` DATETIME NOT NULL,
  `usuarios_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reportes_generados_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_reportes_generados_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auditoria` (
  `id` VARCHAR(36) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `tipo_evento` VARCHAR(100) NOT NULL,
  `entidad` VARCHAR(36) NOT NULL,
  `entidad_id` VARCHAR(100) NOT NULL,
  `cambios_json` JSON NOT NULL,
  `resultado` ENUM('exitoso', 'fallido') NULL,
  `creado_en` DATETIME NOT NULL,
  `usuarios_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_auditoria_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_auditoria_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kanban_movimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kanban_movimientos` (
  `id` VARCHAR(36) NOT NULL,
  `estado_anterior` ENUM('enviado', 'servido', 'preparando', 'cancelado') NOT NULL,
  `creado_en` DATETIME NOT NULL,
  `pedido_items_id` VARCHAR(36) NOT NULL,
  `usuarios_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_kanban_movimientos_pedido_items1_idx` (`pedido_items_id` ASC) VISIBLE,
  INDEX `fk_kanban_movimientos_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_kanban_movimientos_pedido_items1`
    FOREIGN KEY (`pedido_items_id`)
    REFERENCES `mydb`.`pedido_items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kanban_movimientos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cierres_caja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cierres_caja` (
  `id` VARCHAR(36) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `total_efectivo_esperado` DECIMAL(10,2) NOT NULL,
  `total_efectivo_real` DECIMAL(10,2) NOT NULL,
  `diferencia_efectivo` DECIMAL(10,2) NOT NULL,
  `total_general` DECIMAL(10,2) NOT NULL,
  `usuarios_id` VARCHAR(36) NOT NULL,
  `reportes_generados_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cierres_caja_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_cierres_caja_reportes_generados1_idx` (`reportes_generados_id` ASC) VISIBLE,
  CONSTRAINT `fk_cierres_caja_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cierres_caja_reportes_generados1`
    FOREIGN KEY (`reportes_generados_id`)
    REFERENCES `mydb`.`reportes_generados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`merma_motivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`merma_motivos` (
  `id` VARCHAR(36) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mermas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mermas` (
  `id` VARCHAR(36) NOT NULL,
  `cantidad` INT NOT NULL,
  `valor_economico` DECIMAL(10,2) NOT NULL,
  `creado_en` DATETIME NOT NULL,
  `productos_id` VARCHAR(36) NOT NULL,
  `merma_motivos_id` VARCHAR(36) NOT NULL,
  `refrigeradores_id` VARCHAR(36) NOT NULL,
  `movimientos_inventario_id` VARCHAR(36) NOT NULL,
  `usuarios_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mermas_productos1_idx` (`productos_id` ASC) VISIBLE,
  INDEX `fk_mermas_merma_motivos1_idx` (`merma_motivos_id` ASC) VISIBLE,
  INDEX `fk_mermas_refrigeradores1_idx` (`refrigeradores_id` ASC) VISIBLE,
  INDEX `fk_mermas_movimientos_inventario1_idx` (`movimientos_inventario_id` ASC) VISIBLE,
  INDEX `fk_mermas_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_mermas_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `mydb`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mermas_merma_motivos1`
    FOREIGN KEY (`merma_motivos_id`)
    REFERENCES `mydb`.`merma_motivos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mermas_refrigeradores1`
    FOREIGN KEY (`refrigeradores_id`)
    REFERENCES `mydb`.`refrigeradores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mermas_movimientos_inventario1`
    FOREIGN KEY (`movimientos_inventario_id`)
    REFERENCES `mydb`.`movimientos_inventario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mermas_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
